name: 'Build(linux)'

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-ubuntu:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: configure
      run: |
        sudo apt update -y
        sudo bash -x dependencies.sh
        mkdir build
        cd build
        cmake ..
      shell: bash
    - name: make
      run: |
        cd build
        make -j
      shell: bash
    - name: start-metadata-server
      run: |
        cd mooncake-transfer-engine/example/http-metadata-server
        export PATH=$PATH:/usr/local/go/bin
        go run . --addr=:8090 &
      shell: bash
    - name: test
      run: |
        cd build
        MC_METADATA_SERVER=http://127.0.0.1:8090/metadata make test -j
      shell: bash
